theme: minima
title: Security Research by Marin Duroyon
author: Marin Duroyon
email: marinduroyon@gmail.com
description: >-
  A blog detailing my security vulnerabilities and research findings.
baseurl: ""
email: marinduroyon@gmail.com

url: "https://marin-duroyon.github.io"
google_analytics: G-PD5D9TCDPK